import math
import time

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle   - P3n = n(n + 1)/2
# Pentagonal - P5n = n(3n -1)/2
# Hexagonal  - P6n = n(2n -1)
#
# It can be verified that 
# T285 = P165 = H143  
# Find the next triangle number that is also pentagonal and hexagonal.

def Triangular(n):
    return int((n*(n+1))/2)

def Pentagonal(n):
    return int((n*((3*n)-1))/2)

def Hexagonal(n):
    return int(n*((2*n)-1))

def solution():
    start_time = time.time()
    res = 0

    T = 285
    P = 165
    H = 143

    T+=1

    while True:
        t = Triangular(T)

        # Find Pentagonal
        while True:
            p = Pentagonal(P)
            if p > t:
                break
            
            if p != t:
                P+=1
                continue

            # Find Triangular
            while True: 
                h = Hexagonal(H)
                if h > t:
                    break
                elif t == p and t == h:
                    print(f"Process finished --- {time.time() - start_time} seconds ---")
                    return t
               
                H+=1
            P += 1
        T+=1

print(solution())