# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def EvenFibonacciNumbers():
    fib = [1, 1]
    fibEvenSum = 0
    while fib[1] < 4000000:
        if fib[1] % 2 == 0:
            fibEvenSum += fib[1]

        temp = fib[1]
        fib[1] += fib[0]
        fib[0] = temp
    return str(fibEvenSum)

print(EvenFibonacciNumbers())
